// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnFHuSbEm2bKgBOdSkmff98PcXIAziJDM',
    appId: '1:862288001114:web:b3d2181def8c6d373b8063',
    messagingSenderId: '862288001114',
    projectId: 'omnisight-b88c9',
    authDomain: 'omnisight-b88c9.firebaseapp.com',
    storageBucket: 'omnisight-b88c9.firebasestorage.app',
    measurementId: 'G-DP9BNEGK59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF1Q9sTKuFzOsB3MNuQxq3I44D_w56nIs',
    appId: '1:862288001114:android:756d36942a5ab37b3b8063',
    messagingSenderId: '862288001114',
    projectId: 'omnisight-b88c9',
    storageBucket: 'omnisight-b88c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Kn-NQrDQh6VOAsCtgZ9GCEPyuYSZR0M',
    appId: '1:862288001114:ios:582512f74ac089c33b8063',
    messagingSenderId: '862288001114',
    projectId: 'omnisight-b88c9',
    storageBucket: 'omnisight-b88c9.firebasestorage.app',
    iosBundleId: 'com.example.omnisight',
  );
}
